{% set name = "climpred" %}
{% set version = "2.2.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2108e314e8b93a8999e63847a98e8e8783c15f2ae40e945d51ed06cac0bf5646

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >3.6
    - cftime >=1.5.0
    - eofs
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - scipy
    - toolz
    - xarray >=0.19.0
    - xrft
    - dask-core >=2021.10.0
    - xskillscore >=0.0.20
    - netcdf4
    - nc-time-axis >=1.4.0
    - cf_xarray >=0.6.0
    - bias_correction >=0.4
    - xclim !=0.30.0
    - xesmf
    - esmpy =*=mpi*
    - numba >=0.52
    - bottleneck

test:
  imports:
    - climpred

about:
  home: http://github.com/pangeo-data/climpred
  license: MIT
  license_file: LICENSE.txt
  summary: Verification of weather and climate forecasts
  doc_url: http://climpred.readthedocs.io
  dev_url: https://github.com/pangeo-data/climpred

extra:
  recipe-maintainers:
    - bradyrx
    - aaronspring
    - ahuang11
